const companyActions = {
  GET_ALL_COMPANIES_REQUEST: "GET_ALL_COMPANIES_REQUEST",
  GET_ALL_COMPANIES_SUCCESS: "GET_ALL_COMPANIES_SUCCESS",
  GET_ALL_COMPANIES_FAILURE: "GET_ALL_COMPANIES_FAILURE",
  GET_COMPANY_REQUEST: "GET_COMPANY_REQUEST",
  GET_COMPANY_SUCCESS: "GET_COMPANY_SUCCESS",
  GET_COMPANY_FAILURE: "GET_COMPANY_FAILURE",
  ADD_COMPANY_REQUEST: "ADD_COMPANY_REQUEST",
  ADD_COMPANY_SUCCESS: "ADD_COMPANY_SUCCESS",
  ADD_COMPANY_FAILURE: "ADD_COMPANY_FAILURE",
  UPDATE_COMPANY_REQUEST: "UPDATE_COMPANY_REQUEST",
  UPDATE_COMPANY_SUCCESS: "UPDATE_COMPANY_SUCCESS",
  UPDATE_COMPANY_FAILURE: "UPDATE_COMPANY_FAILURE",
  DELETE_COMPANY_REQUEST: "DELETE_COMPANY_REQUEST",
  DELETE_COMPANY_SUCCESS: "DELETE_COMPANY_SUCCESS",
  DELETE_COMPANY_FAILURE: "DELETE_COMPANY_FAILURE",

  getAllCompanies: () => ({
    type: companyActions.GET_ALL_COMPANIES_REQUEST,
  }),
  getCompany: (companyId) => ({
    type: companyActions.GET_COMPANY_REQUEST,
    companyId,
  }),
  addCompany: (newCompany) => ({
    type: companyActions.ADD_COMPANY_REQUEST,
    company: newCompany,
  }),
  updateCompany: (newCompany) => ({
    type: companyActions.UPDATE_COMPANY_REQUEST,
    company: newCompany,
  }),
  deleteCompany: (companyId) => ({
    type: companyActions.DELETE_COMPANY_REQUEST,
    companyId,
  }),
};
export default companyActions;
