const amenityActions = {
  GET_ALL_AMENITIES_REQUEST: "GET_ALL_AMENITIES_REQUEST",
  GET_ALL_AMENITIES_SUCCESS: "GET_ALL_AMENITIES_SUCCESS",
  GET_ALL_AMENITIES_FAILURE: "GET_ALL_AMENITIES_FAILURE",
  GET_AMENITY_REQUEST: "GET_AMENITY_REQUEST",
  GET_AMENITY_SUCCESS: "GET_AMENITY_SUCCESS",
  GET_AMENITY_FAILURE: "GET_AMENITY_FAILURE",
  ADD_AMENITY_REQUEST: "ADD_AMENITY_REQUEST",
  ADD_AMENITY_SUCCESS: "ADD_AMENITY_SUCCESS",
  ADD_AMENITY_FAILURE: "ADD_AMENITY_FAILURE",
  UPDATE_AMENITY_REQUEST: "UPDATE_AMENITY_REQUEST",
  UPDATE_AMENITY_SUCCESS: "UPDATE_AMENITY_SUCCESS",
  UPDATE_AMENITY_FAILURE: "UPDATE_AMENITY_FAILURE",
  DELETE_AMENITY_REQUEST: "DELETE_AMENITY_REQUEST",
  DELETE_AMENITY_SUCCESS: "DELETE_AMENITY_SUCCESS",
  DELETE_AMENITY_FAILURE: "DELETE_AMENITY_FAILURE",

  getAllAmenities: () => ({
    type: amenityActions.GET_ALL_AMENITIES_REQUEST,
  }),
  getAmenity: (amenityId) => ({
    type: amenityActions.GET_AMENITY_REQUEST,
    amenityId,
  }),
  addAmenity: (newAmenity) => ({
    type: amenityActions.ADD_AMENITY_REQUEST,
    amenity: newAmenity,
  }),
  updateAmenity: (newAmenity) => ({
    type: amenityActions.UPDATE_AMENITY_REQUEST,
    amenity: newAmenity,
  }),
  deleteAmenity: (amenityId) => ({
    type: amenityActions.DELETE_AMENITY_REQUEST,
    amenityId,
  }),
};
export default amenityActions;
