name: Frontend CI/CD

on:
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master
  
  repository_dispatch:
    types: [production-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 200
    steps:
    - name: SSH and deploy to Starsofboston Frontend
      uses: appleboy/ssh-action@master
      timeout-minutes: 30
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        command_timeout: 30m
        script: |
          cd /var/starsofboston/stars_nextjs
          sudo npm run build
          sudo pm2 restart next
